### ISSUE TITLE
Les applis crypto ne sont plus séléctionnable.

### ISSUE THREAD

**Issue by Natim** [laboiteproject/lenuage#105]
On peut créer l'app, mais ensuite elle n'apparait pas dans les applis disponibles.
De même dans la liste des apps le taux reste à 0

**Comment by bgaultier** [comment]
Uh oh, je regarde ça !

**Comment by bgaultier** [comment]
Ça devrait marcher (mais peut être pas pour toutes les cryptomonnaies)

**Comment by Natim** [comment]
It's indeed back but it shows the same price for ETH and BTC :confused:
