### ISSUE TITLE
The duration of in the tile should be in milliseconds

### ISSUE THREAD

**Issue by Natim** [laboiteproject/lenuage#69]
`{"duration": 5000}` rather than  `{"duration": 5}`

**Comment by Natim** [comment]
According to the documentation: https://maker.redgick.com/protocole-laboite-lenuage

**Comment by bgaultier** [comment]
Are you sure we want to be that precise ? 😄

**Comment by Natim** [comment]
Yes especially for GIFs support.

**Comment by bgaultier** [comment]
Done :)
a1b9ab6
